management.security.enabled: false
spring.datasource.initialize: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update
hibernate.hbm2ddl.auto: update
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console


startup:
  users:
    - password: dummy
      userName: user1
      email: john.doe@exmaple.com
      firstName: john
      lastName: doe
spring:
  application:
    name: spring-cloud-eureka-cart-client
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
---
spring.profiles: ci

---
spring.profiles: dev

---
spring.profiles: trial

---
spring.profile: prod