management.security.enabled: false

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


---
spring.profiles: ci

---
spring.profiles: dev

---
spring.profiles: trial

---
spring.profile: prod